apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: default
  labels:
    app: reservation-service
spec:
  selector:
    app: reservation-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
