spring:
  data:
    redis:
      host: ${MY_LOCAL_HOST}
      port: 6379
      password: 523108zz
  elasticsearch:
    uris: http://${MY_LOCAL_HOST}:9200
    username: elastic
    password: changeme
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MY_LOCAL_HOST}:3306/travel_search?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 523108zz

api-server:
  host: ${MY_LOCAL_HOST}
  port: 5000
  url: http://${MY_LOCAL_HOST}:5000


kafka-server:
  host: ${MY_LOCAL_HOST}
  port: 39092
  url: http://${MY_LOCAL_HOST}:39092
