spring:
  application:
    name: search
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/travel_search?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 523108zz
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

server:
  port: 8002

springdoc.api-docs.path: /openapi/${spring.application.name} #these urls will used to load the swagger ui of this service by the api gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


