spring:
  application:
    name: search

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


  batch:
    job:
      enabled: true
#    jdbc:
#      initialize-schema: always

server:
  port: 8010



---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: local



