apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service

spec:
  replicas: 1
  selector:
      matchLabels:
        run: gateway-service
        app: gateway-service
  template:
      metadata:
        labels:
            run: gateway-service
            app: gateway-service
      spec:
        containers:
        - name: gateway-service
          image: ghcr.io/jaehyukkk/gateway_service
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: log
              mountPath: /app/logs
          env:
            - name: MY_LOCAL_HOST
              value: "host.minikube.internal"
        volumes:
          - name: log
            hostPath:
              path: /var/log/service-logs
              type: DirectoryOrCreate
        imagePullSecrets:
          - name: ghcr-login-secret
