#spring.application.name=travel_user_service
spring:
  application:
    name: user
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/traval_user?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 523108zz
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 523108zz
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      #      hibernate.default_batch_fetch_size: 1000
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

jwt:
  secret: dGhpcy1pcy1hLXNwcmluZ2Jvb3Qtc2VjdXJpdHktd2l0aC1teXBvcy1hZG1pbi1wcm9qZWN0LWNyZWF0ZWQtYnktaGVvbnlLaW0K

server:
  port: 8001
#  forward-headers-strategy: FRAMEWORK
#  servlet:
#    context-path: /

openapi:
  service:
    title: travel-user-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8000 #api gateway url

springdoc:
  api-docs:
    path: /openapi/${spring.application.name} #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


