#spring.application.name=travel_user_service
spring:
  application:
    name: user
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

jwt:
  secret: dGhpcy1pcy1hLXNwcmluZ2Jvb3Qtc2VjdXJpdHktd2l0aC1teXBvcy1hZG1pbi1wcm9qZWN0LWNyZWF0ZWQtYnktaGVvbnlLaW0K

server:
  port: 8001
#  forward-headers-strategy: FRAMEWORK
#  servlet:
#    context-path: /

openapi:
  service:
    title: travel-user-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8000 #api gateway url

springdoc:
  api-docs:
    path: /openapi/${spring.application.name} #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /${spring.application.name}/swagger-ui.html


---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: local
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost


