spring.cloud.gateway:
  globalcors:
    cors-configurations:
      '[/**]':
        allowedOrigins:
          - http://localhost:3000
        allow-credentials: true
        allowedHeaders: '*'
        allowedMethods:
          - PUT
          - GET
          - POST
          - DELETE
          - OPTIONS
  routes:
  - id: user
    uri: http://localhost:8001
    predicates:
      - Path=/api/*/user/**
  - id: search
    uri: http://localhost:8002
    predicates:
      - Path=/api/*/search/**
  - id: search
    uri: http://localhost:8003
    predicates:
      - Path=/api/*/reservation/**
