apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
  namespace: default
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - /usr/share/filebeat/logs/*.log
        fields_under_root: true
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/usr/share/filebeat/logs/"
    http:
      enabled: true
      host: 0.0.0.0
      port: 5066
    
    logging:
      level: debug
      to_files: true
      files:
        path: /var/log
        name: filebeat
        keepfiles: 7
        permissions: 0644
    output:
      kafka:
        hosts: '${KAFKA_HOST}:39092'
    #    hosts: 'http://168.126.63.1:29092'
        topic: 'service-log'
        partition:
          round_robin:
            reachable_only: false
        required_acks: 1
        compression: gzip
        max_message_bytes: 1000000
