apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: default
  labels:
    app.kubernetes.io/name: filebeat
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: filebeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.1.2
          args:
            # Log to `stderr` instead of `syslog` or `file`
            - "-e"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KAFKA_HOST
              value: "host.minikube.internal"
            - name: KAFKA_PORT
              value: "39092"
          securityContext:
            runAsUser: 0
          resources: {}
          ports:
            - name: internal-http
              containerPort: 5066
          livenessProbe:
            httpGet:
              path: /
              port: internal-http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: internal-http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              name: config
              subPath: filebeat.yml
            - mountPath: /usr/share/filebeat/logs
              name: logs
      volumes:
        - name: config
          configMap:
            name: filebeat-configmap
            defaultMode: 0640
        - name: logs
          hostPath:
            path: /var/log/service-logs
            type: DirectoryOrCreate
